# Generated by Django 5.2.6 on 2025-10-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_is_paid_payment_payment_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_checkout_session_id",
            field=models.CharField(
                blank=True,
                max_length=350,
                null=True,
                verbose_name="Stripe Checkout Session ID",
            ),
        ),
    ]
