# Generated by Django 5.2.6 on 2025-10-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_stripe_checkout_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True, max_length=350, null=True, verbose_name="Ссылка для оплаты"
            ),
        ),
    ]
