# Generated by Django 5.2.6 on 2025-10-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_payment_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка для оплаты"
            ),
        ),
    ]
