# Generated by Django 5.2.6 on 2025-10-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Укажите стоимость курса",
                max_digits=10,
                verbose_name="Цена курса",
            ),
        ),
    ]
